version: "3"
services:
  frontend:
    image: nohyunha95/docker-frontend
    build:
#      dockerfile: nohyunha95/docker-frontend
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    image: nohyunha95/docker-nginx
    build:
#      dockerfile: nohyunha95/docker-nginx
      context: ./nginx
    ports:
      - "80:80"

  backend:
    image: nohyunha95/docker-backend
    build:
#      dockerfile: nohyunha95/docker-backend
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT