version: "3"
services:
  frontend:
    build:
      dockerfile: nohyunha95/docker-frontend
#      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: nohyunha95/docker-nginx
#      context: ./nginx
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: nohyunha95/docker-backend
#      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: echo MYSQL_HOST
      MYSQL_USER: echo $MYSQL_USER
      MYSQL_ROOT_PASSWORD: echo MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: echo MYSQL_DATABASE
      MYSQL_PORT: echo MYSQL_PORT