name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 코드의 내용을 이 파일을 실행하여 action을 수행하는 주체(Github Actions에서 사용하는 VM)가 읽을 수 있도록 허용합니다.
permissions:
  contents: read

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PWD
      run: pwd
    - name: LS
      run: ls
    - name: Build the Docker test image
      run: docker build -t nohyunha95/react-test-app -f ./frontend/Dockerfile.dev ./frontend
  
    - name: Run the Docker test image
      run: docker run -e CI=true nohyunha95/react-test-app npm test

    - name: Build other images
      run: |
        docker build -t nohyunha95/docker-frontend ./frontend
        docker build -t nohyunha95/docker-backend ./backend
        docker build -t nohyunha95/docker-nginx ./nginx
        echo ${{secrets.DOCKER_HUB_PASSWORD}} | docker login -u ${{secrets.DOCKER_HUB_ID}} --password-stdin

        docker push nohyunha95/docker-frontend
        docker push nohyunha95/docker-backend
        docker push nohyunha95/docker-nginx
